# Generated by Django 5.0.2 on 2024-03-05 21:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=255, verbose_name='Category:')),
            ],
            options={
                'verbose_name': 'Category:',
                'verbose_name_plural': 'Category:',
            },
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateTimeField(auto_now=True)),
                ('email', models.CharField(max_length=255, verbose_name='Email:')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone:')),
                ('title', models.CharField(max_length=255, verbose_name='Service title:')),
                ('text', models.TextField()),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='serviceimg/', verbose_name='Image:')),
                ('title_tag', models.CharField(default='Other', max_length=255, verbose_name='Title tag:')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, default='Other', null=True, on_delete=django.db.models.deletion.PROTECT, to='services.category', verbose_name='Status:')),
            ],
            options={
                'verbose_name': 'User Service',
                'verbose_name_plural': 'User Services',
            },
        ),
    ]
