# Generated by Django 5.0.1 on 2024-02-12 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatusService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StatusName', models.CharField(max_length=255, verbose_name='Status name:')),
            ],
            options={
                'verbose_name': 'Status',
                'verbose_name_plural': 'Status',
            },
        ),
        migrations.CreateModel(
            name='UserComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_dt', models.DateTimeField(auto_now=True)),
                ('comment_name', models.CharField(max_length=255, verbose_name='Comment name:')),
                ('comment_text', models.CharField(max_length=255, verbose_name='Comment text:')),
            ],
            options={
                'verbose_name': 'User comment',
                'verbose_name_plural': 'User comments',
            },
        ),
        migrations.CreateModel(
            name='UserService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_dt', models.DateTimeField(auto_now=True)),
                ('user_fname', models.CharField(max_length=255, verbose_name='First Name:')),
                ('user_lname', models.CharField(max_length=255, verbose_name='Last Name:')),
                ('user_email', models.CharField(max_length=255, verbose_name='Email:')),
                ('user_phone', models.CharField(max_length=255, verbose_name='Phone:')),
                ('services_name', models.CharField(max_length=255, verbose_name='Service name:')),
                ('services_text', models.CharField(max_length=255, verbose_name='About services:')),
                ('services_image', models.ImageField(upload_to='serviceimg/')),
                ('services_status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='services.statusservice', verbose_name='Status:')),
            ],
            options={
                'verbose_name': 'User Service',
                'verbose_name_plural': 'User Services',
            },
        ),
    ]
