# Generated by Django 5.0.2 on 2024-03-06 09:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userservice',
            name='likes',
            field=models.ManyToManyField(related_name='services_posts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='category',
            field=models.ForeignKey(blank=True, default='Other', null=True, on_delete=django.db.models.deletion.PROTECT, to='services.category', verbose_name='Category:'),
        ),
    ]
