# Generated by Django 5.0.7 on 2024-07-09 14:46

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_userservice_likes_alter_userservice_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userservice',
            name='email',
            field=models.CharField(max_length=255, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='phone',
            field=models.CharField(max_length=255, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='text',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userservice',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Service title'),
        ),
    ]
